version: '2'
services:
  appserver:
    build: ./go/
    ports:
      - 5000:5000
    volumes:
      - ${APPDIR}:/projects/
  webserver:
    build: ./nginx/
    ports:
      - 8080:80
    links:
      - appserver:app-server
